### ISSUE TITLE
Failing to apply the patch

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/planarity-feedstock#1]
@isuruf something change from when we merged this up to know. See the error below:

```
Hunk #1 FAILED at 38.
Hunk #2 FAILED at 49.
2 out of 2 hunks FAILED -- saving rejects to file c/planarity.h.rej
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/usr/bin/patch', '-p1', '-i', '/Users/travis/build/conda-forge/planarity-feedstock/recipe/extern.patch']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1484, in build_tree
    config=config)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 984, in build
    assert not need_source_download, "Source download failed.  Please investigate."
AssertionError: Source download failed.  Please investigate.
```

This is stuck on `master` b/c of this. I will remove it manually from there since the feedstock creation worked.

**Comment by isuruf** [comment]
Arghh. This is a CRLF/LF issue. I'll try to fix it.

**Comment by ocefpaf** [comment]
:+1:

**Comment by malcook** [comment]
+1

"Source download failed.  Please investigate." is too specific of a message to emit when the true error is failure to apply a patch.  

...especially as just happened to me, where the source was previously downloaded and cached, which just made this message all the more confusing.
